### ISSUE TITLE
Support building static library

### ISSUE THREAD

**Issue by kivikakk** [libfuse/libfuse#383]
From #354:

I found that when building libfuse as a static library (`meson configure --default-library static`), I invariably hit errors like this when trying to use it:

```
libtool: link:  gcc -shared  -fPIC -DPIC  .libs/projfs.o .libs/projfs_vfsapi.o   -lfuse3 -ldl -lpthread  -g -O2   -Wl,-soname -Wl,libprojfs.so.0 -Wl,-version-script -Wl,.libs/libprojfs.ver -o .libs/libprojfs.so.0.0.0
/usr/bin/ld: .libs/libprojfs.so.0.0.0: version node not found for symbol fuse_loop_mt@@FUSE_3.2
/usr/bin/ld: failed to set dynamic section sizes: Bad value
collect2: error: ld returned 1 exit status
```

This is without adjusting the calling code at all. Indeed, even if I drop all calls to `fuse_loop_mt` in the calling code, this still happens, so I guess some versioning weirdness left inside `libfuse.a` is producing this when linking.

**Comment by hselin** [comment]
Just FYI.

With the latest code (release 3.10.0) I got the following errors building libfuse3.a with meson 0.45.1

```
[27/29] Linking target util/mount.fuse3.
FAILED: util/mount.fuse3 
gcc-9  -o util/mount.fuse3 'util/mount.fuse3@exe/mount.fuse.c.o' -Wl,--no-undefined -Wl,--as-needed -Wl,--start-group lib/libfuse3.a -ldl -lrt -Wl,--end-group  
/usr/bin/ld: lib/libfuse3.a(fuse_loop_mt.c.o): undefined reference to symbol 'pthread_sigmask@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
[29/29] Linking target test/test_setattr.
```

But after upgrading meson to 0.55.3, I was able to generate libfuse3.a and it worked with my application without any error.

**Comment by Nikratio** [comment]
Cool, thanks for letting me know! I guess this was a Meson bug then.
