### ISSUE TITLE
3.17.1~rc0 breaks the build of grub2

### ISSUE THREAD

**Issue by gcsideal** [libfuse/libfuse#1134]
I was testing other software if those still compile with the 3.17.1~rc0 release of fuse. So far all seems to be fine except grub2 which fails with the following.
Compiling grub-core/osdep/init.c
In file included from ../../util/grub-mount.c:36:
/usr/include/fuse3/fuse.h: In function ‘fuse_main_real’:
/usr/include/fuse3/fuse.h:899:13: error: nested extern declaration of ‘fuse_main_real_versioned’ [-Werror=nested-externs]
  899 |         int fuse_main_real_versioned(int argc, char *argv[],
      |             ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/fuse3/fuse.h: In function ‘fuse_main_fn’:
/usr/include/fuse3/fuse.h:975:13: error: nested extern declaration of ‘fuse_main_real_versioned’ [-Werror=nested-externs]
  975 |         int fuse_main_real_versioned(int argc, char *argv[],
      |             ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/fuse3/fuse.h: In function ‘fuse_new_fn’:
/usr/include/fuse3/fuse.h:1070:22: error: nested extern declaration of ‘_fuse_new_31’ [-Werror=nested-externs]
 1070 |         struct fuse *_fuse_new_31(struct fuse_args *args,
      |                      ^~~~~~~~~~~~

Can this be fixed?

**Comment by bsbernd** [comment]
Hmm, that is a pity, I had done it on purpose, so that fuse_main_real_versioned() is not exposed. Looks like that doesn't work well. I could probably try to disable the warning with pragmas, but also not beautiful - I going to declare these _versioned functions globally later on today. Thank you for reporting the issue.
