### ISSUE TITLE
sshfs and fuse can run properly on AIX 6.1??

### ISSUE THREAD

**Issue by markosferreira** [libfuse/libfuse#34]
I have tried compile it on aix 6.1 just to test and got some errors.
Do you think sshfs/fuse can work fine on aix 6.1?
./configure works fine, however I have error below during make -j8

#: make -j8
Making all in include
        make  all-am
Target "all-am" is up to date.
Making all in lib
  CC       fuse.lo
  CC       fuse_kern_chan.lo
  CC       fuse_loop.lo
  CC       fuse_loop_mt.lo
  CC       fuse_lowlevel.lo
  CC       fuse_mt.lo
  CC       fuse_opt.lo
  CC       fuse_session.lo
  CC       fuse_signals.lo
  CC       buffer.lo
  CC       cuse_lowlevel.lo
  CC       helper.lo
  CC       modules/subdir.lo
  CC       modules/iconv.lo
  CC       mount.lo
  CC       mount_util.lo
  CC       ulockmgr.lo
fuse.c: In function 'convert_statfs_old':
fuse.c:1535:27: error: 'struct statfs' has no member named 'f_namelen'
  stbuf->f_namemax = oldbuf->f_namelen;
                           ^
fuse.c: In function 'fuse_fs_utimens':
fuse.c:2154:5: warning: format '%li' expects argument of type 'long int', but argument 4 has type 'time_t' [-Wformat=]
     tv[1].tv_sec, tv[1].tv_nsec);
     ^
fuse.c:2154:5: warning: format '%li' expects argument of type 'long int', but argument 6 has type 'time_t' [-Wformat=]
fuse.c:2162:5: warning: format '%li' expects argument of type 'long int', but argument 4 has type 'time_t' [-Wformat=]
     tv[0].tv_sec, tv[1].tv_sec);
     ^
fuse.c:2162:5: warning: format '%li' expects argument of type 'long int', but argument 5 has type 'time_t' [-Wformat=]
fuse.c: In function 'locks_insert':
fuse.c:3745:10: warning: comparison is always true due to limited range of data type [-Wtype-limits]
      lock->end != OFFSET_MAX) {
          ^
fuse.c: In function 'lock_to_flock':
fuse.c:3827:8: warning: comparison is always false due to limited range of data type [-Wtype-limits]
   (lock->end == OFFSET_MAX) ? 0 : lock->end - lock->start + 1;
        ^
Assembler:
/tmp//ccBPTgBf.s: line 562: Invalid relocation type: .
/tmp//ccBPTgBf.s: line 562: invalid opcode or pseudo-op
buffer.c: In function 'fuse_buf_splice':
buffer.c:171:19: error: 'SPLICE_F_MOVE' undeclared (first use in this function)
   splice_flags |= SPLICE_F_MOVE;
                   ^
buffer.c:171:19: note: each undeclared identifier is reported only once for each function it appears in
buffer.c:173:19: error: 'SPLICE_F_NONBLOCK' undeclared (first use in this function)
   splice_flags |= SPLICE_F_NONBLOCK;
                   ^
buffer.c:185:3: warning: implicit declaration of function 'splice' [-Wimplicit-function-declaration]
   res = splice(src->fd, srcpos, dst->fd, dstpos, len,
   ^
make: 1254-004 The error code from the last command is mount.c:127:23: fatal error: sys/mount.h: No such file or directory
 #include <sys/mount.h>
                       ^
compilation terminated.
.

Stop.
make: 1254-004 The error code from the last command is 1.

Stop.
#: modules/iconv.c: In function 'iconv_convpath':
modules/iconv.c:69:8: warning: passing argument 2 of 'libiconv' from incompatible pointer type [enabled by default]
        &pathlen, &p, &plen);
        ^
In file included from modules/iconv.c:17:0:
/opt/freeware/include/iconv.h:83:15: note: expected 'const char **' but argument is of type 'char **'
 extern size_t iconv (iconv_t cd, const char* * inbuf, size_t *inbytesleft, char* * outbuf, size_t *outbytesleft);
               ^
fuse_lowlevel.c: In function 'fuse_ll_receive_buf':
fuse_lowlevel.c:2612:2: warning: implicit declaration of function 'splice' [-Wimplicit-function-declaration]
  res = splice(fuse_chan_fd(ch), NULL, llp->pipe[1], NULL, bufsize, 0);
  ^
fuse_lowlevel.c: In function 'fuse_req_getgroups':
fuse_lowlevel.c:2839:35: warning: unused parameter 'req' [-Wunused-parameter]
 int fuse_req_getgroups(fuse_req_t req, int size, gid_t list[])
                                   ^
fuse_lowlevel.c:2839:44: warning: unused parameter 'size' [-Wunused-parameter]
 int fuse_req_getgroups(fuse_req_t req, int size, gid_t list[])
                                            ^
fuse_lowlevel.c:2839:56: warning: unused parameter 'list' [-Wunused-parameter]
 int fuse_req_getgroups(fuse_req_t req, int size, gid_t list[])
                                                        ^
fuse_lowlevel.c: In function 'convert_statfs_compat':
fuse_lowlevel.c:2866:28: error: 'const struct statfs' has no member named 'f_namelen'
  buf->f_namemax = compatbuf->f_namelen;
                            ^
mount_util.c:25:23: fatal error: sys/mount.h: No such file or directory
 #include <sys/mount.h>
                       ^
compilation terminated.
Assembler:
/tmp//cc5o0lQx.s: line 573: Invalid relocation type: .
/tmp//cc5o0lQx.s: line 573: invalid opcode or pseudo-op
/tmp//cc5o0lQx.s: line 574: Invalid relocation type: FUSE_.
/tmp//cc5o0lQx.s: line 574: invalid opcode or pseudo-op
/tmp//cc5o0lQx.s: line 574: Error In Syntax 
/tmp//cc5o0lQx.s: line 575: Invalid relocation type: .
/tmp//cc5o0lQx.s: line 575: invalid opcode or pseudo-op
/tmp//cc5o0lQx.s: line 576: Invalid relocation type: .
/tmp//cc5o0lQx.s: line 576: invalid opcode or pseudo-op
/tmp//cc5o0lQx.s: line 577: Invalid relocation type: FUSE_.
/tmp//cc5o0lQx.s: line 577: invalid opcode or pseudo-op
/tmp//cc5o0lQx.s: line 577: Error In Syntax 
/tmp//cc5o0lQx.s: line 578: Invalid relocation type: FUSE_.
/tmp//cc5o0lQx.s: line 578: invalid opcode or pseudo-op
/tmp//cc5o0lQx.s: line 578: Error In Syntax 
/tmp//cc5o0lQx.s: line 579: Invalid relocation type: FUSE_.
/tmp//cc5o0lQx.s: line 579: invalid opcode or pseudo-op
/tmp//cc5o0lQx.s: line 579: Error In Syntax 
/tmp//cc5o0lQx.s: line 580: Invalid relocation type: FUSE_.
/tmp//cc5o0lQx.s: line 580: invalid opcode or pseudo-op
/tmp//cc5o0lQx.s: line 580: Error In Syntax 
/tmp//cc5o0lQx.s: line 581: Invalid relocation type: FUSE_.
/tmp//cc5o0lQx.s: line 581: invalid opcode or pseudo-op
/tmp//cc5o0lQx.s: line 581: Error In Syntax 
Assembler:
/tmp//ccDwzKNl.s: line 516: Invalid relocation type: FUSE_.
/tmp//ccDwzKNl.s: line 516: invalid opcode or pseudo-op
/tmp//ccDwzKNl.s: line 516: Error In Syntax 
Assembler:
/tmp//ccvGpP5X.s: line 568: Invalid relocation type: FUSE_.
/tmp//ccvGpP5X.s: line 568: invalid opcode or pseudo-op
/tmp//ccvGpP5X.s: line 568: Error In Syntax

**Comment by Nikratio** [comment]
Please use the FUSE mailing list for discussions.

For FUSE to work on AIX, you most of all need kernel support. I don't think AIX has that, but I know nearly nothing about AIX.
